FROM arm32v6/alpine

LABEL maintainer="akshmakov@gmail.com"

RUN apk --no-cache add socat bash

COPY serialport-server.sh /usr/local/bin/serialport-server

EXPOSE 2000

ENTRYPOINT [ "serialport-server" ]
