FROM arm32v7/debian:jessie

LABEL maintainer="akshmakov@gmail.com"

ENV DEBIAN_FRONTEND noninteractive 

RUN apt-get update && \ 
    apt-get install -y socat  && \
    rm -rf /var/lib/apt/lists/*

COPY serialport-server.sh /usr/local/bin/serialport-server

EXPOSE 2000

ENTRYPOINT [ "serialport-server" ]

    
    
